name: wow
description: Salon Online Booking
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
    dartz: ^0.10.1
    dio: ^4.0.6
    equatable: ^2.0.3
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter
    flutter_bloc: ^8.0.1
    flutter_spinkit: ^5.1.0
    fluttertoast: ^8.0.9
    get_it: ^7.2.0
    http: ^0.13.4
    internet_connection_checker: ^0.0.1+4
    shared_preferences: ^2.0.15
    intl_phone_field: ^3.0.0
    cupertino_icons: ^1.0.2
    google_maps_flutter: ^2.4.0
    geolocator: ^9.0.2
    geocoding: ^2.0.5
    lottie: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - lang/ar.json
   - lang/en.json
   - assets/images/
   - assets/icons/
  fonts:
      - family: Tajawal
        fonts:
          - asset: assets/fonts/Tajawal-Black.ttf
            weight: 900
          - asset: assets/fonts/Tajawal-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Tajawal-Bold.ttf
            weight: 700
          - asset: assets/fonts/Tajawal-Medium.ttf
            weight: 500
          - asset: assets/fonts/Tajawal-Regular.ttf
            weight: 400
          - asset: assets/fonts/Tajawal-Light.ttf
            weight: 300
          - asset: assets/fonts/Tajawal-ExtraLight.ttf
            weight: 200